---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull rahulpuram123/calculator:latest
    - name: Running container
      shell: docker create -it  --name calculator rahulpuram123/calculator
